/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/text_analyzer.rs:80

CREATE TABLE tokenizer_catalog.text_analyzer (
    name TEXT NOT NULL UNIQUE PRIMARY KEY,
    config TEXT NOT NULL,
    owner NAME NOT NULL DEFAULT CURRENT_USER
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/synonym.rs:55

CREATE TABLE tokenizer_catalog.synonym (
    name TEXT NOT NULL UNIQUE PRIMARY KEY,
    config TEXT NOT NULL,
    owner NAME NOT NULL DEFAULT CURRENT_USER
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/tokenizer.rs:83

CREATE TABLE tokenizer_catalog.tokenizer (
    name TEXT NOT NULL UNIQUE PRIMARY KEY,
    config TEXT NOT NULL,
    owner NAME NOT NULL DEFAULT CURRENT_USER
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/mod.rs:54

CREATE TABLE tokenizer_catalog.model (
    name TEXT NOT NULL UNIQUE PRIMARY KEY,
    config TEXT NOT NULL,
    owner NAME NOT NULL DEFAULT CURRENT_USER
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:435

CREATE FUNCTION tokenizer_catalog.custom_model_insert_trigger()
RETURNS TRIGGER AS $$
DECLARE
    tokenizer_name TEXT := TG_ARGV[0];
    target_column TEXT := TG_ARGV[1];
    text_analyzer TEXT := TG_ARGV[2];
BEGIN
    EXECUTE format('
    WITH 
    new_tokens AS (
        SELECT unnest(tokenizer_catalog.apply_text_analyzer_for_custom_model($1.%I, %L)) AS token
    ),
    to_insert AS (
        SELECT token FROM new_tokens
        WHERE NOT EXISTS (
            SELECT 1 FROM tokenizer_catalog.%I WHERE token = new_tokens.token
        )
    )
    INSERT INTO tokenizer_catalog.%I (token) SELECT token FROM to_insert ON CONFLICT (token) DO NOTHING', target_column, text_analyzer, 'model_' || tokenizer_name, 'model_' || tokenizer_name) USING NEW;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog;
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:465

CREATE FUNCTION tokenizer_catalog.create_custom_model_tokenizer_and_trigger(
tokenizer_name TEXT, model_name TEXT, text_analyzer_name TEXT, table_name TEXT, source_column TEXT, target_column TEXT)
RETURNS VOID AS $body$
DECLARE
    table_parts TEXT[];
    qualified_table TEXT;
BEGIN
    table_parts := pg_catalog.string_to_array(table_name, '.');
    IF pg_catalog.array_length(table_parts, 1) = 1 THEN
        qualified_table := pg_catalog.format('%I.%I', pg_catalog.current_schema(), table_parts[1]);
    ELSIF pg_catalog.array_length(table_parts, 1) = 2 THEN
        qualified_table := pg_catalog.format('%I.%I', table_parts[1], table_parts[2]);
    ELSE
        RAISE EXCEPTION 'Invalid table reference: %', table_name;
    END IF;

    EXECUTE pg_catalog.format('SELECT tokenizer_catalog.create_custom_model(%L, $$
        table = %L
        column = %L
        text_analyzer = %L
        $$)', model_name, table_name, source_column, text_analyzer_name);
    EXECUTE pg_catalog.format('SELECT tokenizer_catalog.create_tokenizer(%L, $$
        text_analyzer = %L
        model = %L
        $$)', tokenizer_name, text_analyzer_name, model_name);
    EXECUTE pg_catalog.format('UPDATE %s SET %I = tokenizer_catalog.tokenize(%I, %L)', qualified_table, target_column, source_column, tokenizer_name);
    EXECUTE pg_catalog.format('CREATE TRIGGER "model_%s_trigger_insert" BEFORE INSERT OR UPDATE OF %I ON %s FOR EACH ROW EXECUTE FUNCTION tokenizer_catalog.custom_model_tokenizer_set_target_column_trigger(%L, %I, %I)', model_name, source_column, qualified_table, tokenizer_name, source_column, target_column);
END;
$body$ LANGUAGE plpgsql;
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/stopwords.rs:43

CREATE TABLE tokenizer_catalog.stopwords (
    name TEXT NOT NULL UNIQUE PRIMARY KEY,
    config TEXT NOT NULL,
    owner NAME NOT NULL DEFAULT CURRENT_USER
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/text_analyzer.rs:182
-- pg_tokenizer::text_analyzer::__pg_tokenizer_apply_text_analyzer
CREATE  FUNCTION "__pg_tokenizer_apply_text_analyzer"(
	"text" TEXT, /* &str */
	"text_analyzer_name" TEXT /* &str */
) RETURNS TEXT[] /* alloc::vec::Vec<alloc::string::String> */
IMMUTABLE STRICT SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'apply_text_analyzer_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/text_analyzer.rs:218
-- requires:
--   apply_text_analyzer_internal


CREATE FUNCTION tokenizer_catalog.apply_text_analyzer(text TEXT, text_analyzer_name TEXT)
RETURNS TEXT[]
LANGUAGE sql IMMUTABLE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_apply_text_analyzer($1, $2); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:359
-- pg_tokenizer::model::custom::__pg_tokenizer_apply_text_analyzer_for_custom_model
CREATE  FUNCTION "__pg_tokenizer_apply_text_analyzer_for_custom_model"(
	"text" TEXT, /* &str */
	"text_analyzer_name" TEXT /* &str */
) RETURNS TEXT[] /* alloc::vec::Vec<alloc::string::String> */
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'apply_text_analyzer_for_custom_model_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:500
-- requires:
--   apply_text_analyzer_for_custom_model_internal


CREATE FUNCTION tokenizer_catalog.apply_text_analyzer_for_custom_model(text TEXT, text_analyzer_name TEXT)
RETURNS TEXT[]
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_apply_text_analyzer_for_custom_model($1, $2); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:249
-- pg_tokenizer::model::custom::__pg_tokenizer_create_custom_model_catalog
CREATE  FUNCTION "__pg_tokenizer_create_custom_model_catalog"(
	"call_token" TEXT, /* &str */
	"name" TEXT, /* &str */
	"config" TEXT, /* &str */
	"owner" TEXT, /* &str */
	"tokens" TEXT[] /* alloc::vec::Vec<alloc::string::String> */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_custom_model_catalog_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/huggingface.rs:31
-- pg_tokenizer::model::huggingface::__pg_tokenizer_create_huggingface_model
CREATE  FUNCTION "__pg_tokenizer_create_huggingface_model"(
	"name" TEXT, /* &str */
	"config" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_huggingface_model_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/huggingface.rs:95
-- requires:
--   create_huggingface_model_internal


CREATE FUNCTION tokenizer_catalog.create_huggingface_model(name TEXT, config TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_create_huggingface_model($1, $2, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/lindera.rs:38
-- pg_tokenizer::model::lindera::__pg_tokenizer_create_lindera_model
CREATE  FUNCTION "__pg_tokenizer_create_lindera_model"(
	"name" TEXT, /* &str */
	"config" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_lindera_model_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/lindera.rs:101
-- requires:
--   create_lindera_model_internal


CREATE FUNCTION tokenizer_catalog.create_lindera_model(name TEXT, config TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_create_lindera_model($1, $2, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/stopwords.rs:86
-- pg_tokenizer::token_filter::stopwords::__pg_tokenizer_create_stopwords
CREATE  FUNCTION "__pg_tokenizer_create_stopwords"(
	"name" TEXT, /* &str */
	"config" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_stopwords_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/stopwords.rs:186
-- requires:
--   create_stopwords_internal


CREATE FUNCTION tokenizer_catalog.create_stopwords(name TEXT, config TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_create_stopwords($1, $2, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/synonym.rs:97
-- pg_tokenizer::token_filter::synonym::__pg_tokenizer_create_synonym
CREATE  FUNCTION "__pg_tokenizer_create_synonym"(
	"name" TEXT, /* &str */
	"config" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_synonym_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/synonym.rs:157
-- requires:
--   create_synonym_internal


CREATE FUNCTION tokenizer_catalog.create_synonym(name TEXT, config TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_create_synonym($1, $2, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/text_analyzer.rs:123
-- pg_tokenizer::text_analyzer::__pg_tokenizer_create_text_analyzer
CREATE  FUNCTION "__pg_tokenizer_create_text_analyzer"(
	"name" TEXT, /* &str */
	"config" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_text_analyzer_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/text_analyzer.rs:194
-- requires:
--   create_text_analyzer_internal


CREATE FUNCTION tokenizer_catalog.create_text_analyzer(name TEXT, config TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_create_text_analyzer($1, $2, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/tokenizer.rs:122
-- pg_tokenizer::tokenizer::__pg_tokenizer_create_tokenizer
CREATE  FUNCTION "__pg_tokenizer_create_tokenizer"(
	"name" TEXT, /* &str */
	"config" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_tokenizer_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tokenizer.rs:197
-- requires:
--   create_tokenizer_internal


CREATE FUNCTION tokenizer_catalog.create_tokenizer(name TEXT, config TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_create_tokenizer($1, $2, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:330
-- pg_tokenizer::model::custom::__pg_tokenizer_drop_custom_model_catalog
CREATE  FUNCTION "__pg_tokenizer_drop_custom_model_catalog"(
	"call_token" TEXT, /* &str */
	"name" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_custom_model_catalog_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/huggingface.rs:68
-- pg_tokenizer::model::huggingface::__pg_tokenizer_drop_huggingface_model
CREATE  FUNCTION "__pg_tokenizer_drop_huggingface_model"(
	"name" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_huggingface_model_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/huggingface.rs:107
-- requires:
--   drop_huggingface_model_internal


CREATE FUNCTION tokenizer_catalog.drop_huggingface_model(name TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_drop_huggingface_model($1, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/lindera.rs:74
-- pg_tokenizer::model::lindera::__pg_tokenizer_drop_lindera_model
CREATE  FUNCTION "__pg_tokenizer_drop_lindera_model"(
	"name" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_lindera_model_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/lindera.rs:113
-- requires:
--   drop_lindera_model_internal


CREATE FUNCTION tokenizer_catalog.drop_lindera_model(name TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_drop_lindera_model($1, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/stopwords.rs:121
-- pg_tokenizer::token_filter::stopwords::__pg_tokenizer_drop_stopwords
CREATE  FUNCTION "__pg_tokenizer_drop_stopwords"(
	"name" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_stopwords_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/stopwords.rs:198
-- requires:
--   drop_stopwords_internal


CREATE FUNCTION tokenizer_catalog.drop_stopwords(name TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_drop_stopwords($1, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/synonym.rs:132
-- pg_tokenizer::token_filter::synonym::__pg_tokenizer_drop_synonym
CREATE  FUNCTION "__pg_tokenizer_drop_synonym"(
	"name" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_synonym_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/synonym.rs:169
-- requires:
--   drop_synonym_internal


CREATE FUNCTION tokenizer_catalog.drop_synonym(name TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_drop_synonym($1, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/text_analyzer.rs:157
-- pg_tokenizer::text_analyzer::__pg_tokenizer_drop_text_analyzer
CREATE  FUNCTION "__pg_tokenizer_drop_text_analyzer"(
	"name" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_text_analyzer_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/text_analyzer.rs:206
-- requires:
--   drop_text_analyzer_internal


CREATE FUNCTION tokenizer_catalog.drop_text_analyzer(name TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_drop_text_analyzer($1, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/tokenizer.rs:156
-- pg_tokenizer::tokenizer::__pg_tokenizer_drop_tokenizer
CREATE  FUNCTION "__pg_tokenizer_drop_tokenizer"(
	"name" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS void
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_tokenizer_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tokenizer.rs:209
-- requires:
--   drop_tokenizer_internal


CREATE FUNCTION tokenizer_catalog.drop_tokenizer(name TEXT)
RETURNS VOID
LANGUAGE sql VOLATILE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_drop_tokenizer($1, CASE WHEN pg_catalog.current_setting('role') = 'none' THEN session_user::text ELSE pg_catalog.current_setting('role') END); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:309
-- pg_tokenizer::model::custom::__pg_tokenizer_get_custom_model_config
CREATE  FUNCTION "__pg_tokenizer_get_custom_model_config"(
	"call_token" TEXT, /* &str */
	"name" TEXT, /* &str */
	"owner" TEXT /* &str */
) RETURNS TEXT /* alloc::string::String */
STRICT VOLATILE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_custom_model_config_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tokenizer.rs:181
-- pg_tokenizer::tokenizer::__pg_tokenizer_tokenize
CREATE  FUNCTION "__pg_tokenizer_tokenize"(
	"text" TEXT, /* &str */
	"tokenizer_name" TEXT /* &str */
) RETURNS INT[] /* alloc::vec::Vec<i32> */
STRICT STABLE SECURITY DEFINER PARALLEL SAFE 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tokenize_internal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tokenizer.rs:221
-- requires:
--   tokenize_internal


CREATE FUNCTION tokenizer_catalog.tokenize(text TEXT, tokenizer_name TEXT)
RETURNS INTEGER[]
LANGUAGE sql STABLE PARALLEL SAFE SECURITY DEFINER
SET search_path = tokenizer_catalog, pg_catalog
AS $$ SELECT tokenizer_catalog.__pg_tokenizer_tokenize($1, $2); $$;
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/mod.rs:65
-- requires:
--   create_tokenizer_wrapper_sql
--   drop_tokenizer_wrapper_sql
--   tokenize_wrapper_sql
--   create_text_analyzer_wrapper_sql
--   drop_text_analyzer_wrapper_sql
--   apply_text_analyzer_wrapper_sql
--   create_stopwords_wrapper_sql
--   drop_stopwords_wrapper_sql
--   create_synonym_wrapper_sql
--   drop_synonym_wrapper_sql
--   create_huggingface_model_wrapper_sql
--   drop_huggingface_model_wrapper_sql
--   create_lindera_model_wrapper_sql
--   drop_lindera_model_wrapper_sql
--   apply_text_analyzer_for_custom_model_wrapper_sql


REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_create_tokenizer(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_drop_tokenizer(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_tokenize(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_create_text_analyzer(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_drop_text_analyzer(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_apply_text_analyzer(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_create_stopwords(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_drop_stopwords(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_create_synonym(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_drop_synonym(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_create_huggingface_model(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_drop_huggingface_model(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_create_lindera_model(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_drop_lindera_model(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION tokenizer_catalog.__pg_tokenizer_apply_text_analyzer_for_custom_model(TEXT, TEXT) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/stopwords.rs:171
-- pg_tokenizer::token_filter::stopwords::_pg_tokenizer_stopwords_init
CREATE  FUNCTION "_pg_tokenizer_stopwords_init"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', '_pg_tokenizer_stopwords_init_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/token_filter/stopwords.rs:178
-- requires:
--   stopwords_table
--   _pg_tokenizer_stopwords_init


    SELECT tokenizer_catalog._pg_tokenizer_stopwords_init();
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/mod.rs:178
-- pg_tokenizer::model::add_preload_model
CREATE  FUNCTION "add_preload_model"(
	"name" TEXT /* &str */
) RETURNS void
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'add_preload_model_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:135
-- pg_tokenizer::model::custom::create_custom_model
CREATE  FUNCTION "create_custom_model"(
	"name" TEXT, /* &str */
	"config" TEXT /* &str */
) RETURNS void
STRICT VOLATILE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'create_custom_model_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:197
-- pg_tokenizer::model::custom::drop_custom_model
CREATE  FUNCTION "drop_custom_model"(
	"name" TEXT /* &str */
) RETURNS void
STRICT VOLATILE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_custom_model_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/mod.rs:207
-- pg_tokenizer::model::list_preload_models
CREATE  FUNCTION "list_preload_models"() RETURNS TEXT[] /* alloc::vec::Vec<alloc::string::String> */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_preload_models_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/mod.rs:192
-- pg_tokenizer::model::remove_preload_model
CREATE  FUNCTION "remove_preload_model"(
	"name" TEXT /* &str */
) RETURNS void
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'remove_preload_model_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/model/custom.rs:512
-- pg_tokenizer::model::custom::custom_model_tokenizer_set_target_column_trigger
CREATE FUNCTION "custom_model_tokenizer_set_target_column_trigger"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'custom_model_tokenizer_set_target_column_trigger_wrapper';
/* </end connected objects> */

